name: 'voy_case_study'
version: '1.0.0'
config-version: 2

profile: 'voy_case_study'

model-paths: ["models"]
test-paths: ["tests"]
macro-paths: ["macros"]

clean-targets:
  - "target"
  - "dbt_packages"

vars:
# `activity.csv`runs to 2024-08-16, but `current_date` is pinned to 2024-07-24 
# in order to simulate the use case of having subscriptions that run past the current
# date. The data in the last 3 weeks of the dataset looks to behave differently
# than the historic data, looking more like subscription snapshot data for 
# active subscriptions. More detail is needed on how this data is generated
# in order to decide if the method of combining the records for a subscription
# ID with the same start date applies correctly to it.
  current_date: "date('2024-07-24')"

models:
  voy_case_study:
    staging:
      +materialized: view
    core:
      +materialized: table
    marts:
      +materialized: table
